import { defineContentType } from '@govea/core'

export const applicationContentType = defineContentType({
  name: 'application',
  label: 'Application',
  labelPlural: 'Applications',
  description: 'Technology that enables organizational capabilities. Every application must trace to at least one capability.',
  icon: 'layout-grid',
  titleField: 'name',
  workflow: true,
  audit: true,
  permissions: ['admin', 'contributor'],
  fields: [
    {
      name: 'name',
      label: 'Application Name',
      type: 'text',
      required: true,
      placeholder: 'e.g. Tyler Munis ERP, Accela Permitting',
    },
    {
      name: 'description',
      label: 'Description',
      type: 'richtext',
    },
    {
      name: 'vendor',
      label: 'Vendor',
      type: 'text',
      placeholder: 'e.g. Tyler Technologies',
    },
    {
      name: 'version',
      label: 'Version',
      type: 'text',
      placeholder: 'e.g. 2024.1',
    },
    {
      name: 'lifecycleStatus',
      label: 'Lifecycle Status',
      type: 'select',
      required: true,
      options: [
        { label: 'Current — actively supported and in use', value: 'current' },
        { label: 'Aging — functional but approaching end of life', value: 'aging' },
        { label: 'Sunset — replacement in progress', value: 'sunset' },
        { label: 'Decommissioned — no longer in use', value: 'decommissioned' },
        { label: 'Planned — approved but not yet deployed', value: 'planned' },
      ],
    },
    {
      name: 'businessCriticality',
      label: 'Business Criticality',
      type: 'select',
      options: [
        { label: 'Critical — outage stops government services', value: 'critical' },
        { label: 'High — significant operational impact', value: 'high' },
        { label: 'Medium — moderate impact, workarounds exist', value: 'medium' },
        { label: 'Low — minimal impact', value: 'low' },
      ],
    },
    {
      name: 'technicalDebtScore',
      label: 'Technical Debt Score',
      type: 'select',
      options: [
        { label: '1 — Minimal debt, well-maintained', value: '1' },
        { label: '2 — Some debt, manageable', value: '2' },
        { label: '3 — Moderate debt, needs attention', value: '3' },
        { label: '4 — Significant debt, limits capability', value: '4' },
        { label: '5 — Critical debt, replacement priority', value: '5' },
      ],
    },
    {
      name: 'hostingModel',
      label: 'Hosting Model',
      type: 'select',
      options: [
        { label: 'On-Premises', value: 'on-prem' },
        { label: 'Cloud (IaaS/PaaS)', value: 'cloud' },
        { label: 'SaaS', value: 'saas' },
        { label: 'Hybrid', value: 'hybrid' },
      ],
    },
    {
      name: 'annualCost',
      label: 'Annual Cost (USD)',
      type: 'number',
      description: 'Total annual cost including licensing, hosting, and support.',
    },
    {
      name: 'contractExpiry',
      label: 'Contract Expiry Date',
      type: 'date',
    },
    {
      name: 'owningDepartment',
      label: 'Owning Department',
      type: 'text',
    },
    {
      name: 'capabilities',
      label: 'Capabilities Enabled',
      type: 'relation',
      to: 'capability',
      many: true,
      required: true,
      description: 'Which capabilities does this application enable? At least one is required.',
    },
    {
      name: 'personas',
      label: 'Direct Users',
      type: 'relation',
      to: 'persona',
      many: true,
      description: 'Which personas directly interact with this application?',
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'richtext',
    },
  ],
})
