// Scale test fixtures — 300 capabilities × 500 applications across 20 domains.
// Programmatically generated so the file stays compact and distributions are tunable.
// Purpose: stress-test portfolio views (heatmap, risk portfolio, architecture vision)
// with a realistic large-agency application inventory volume.

export const SCALE_ORG = { slug: 'scale-test', name: 'Metro Scale Test' }

export const SCALE_USERS = [
  { email: 'scale@govea.dev', name: 'Scale Test Admin', role: 'admin' as const },
]

// ── Distributions (length 25 — one slot per app per domain) ─────────────────

const LIFECYCLE = [
  'active','active','active','active','active','active','active','active','active','active',
  'active','active','active','active',
  'planned','planned','planned','planned','planned',
  'sunset','sunset','sunset','sunset',
  'decommissioned','decommissioned',
] as const

const HOSTING = [
  'saas','saas','saas','saas','saas','saas','saas','saas','saas','saas','saas','saas',
  'on-prem','on-prem','on-prem','on-prem','on-prem','on-prem','on-prem','on-prem','on-prem',
  'hybrid','hybrid','hybrid','hybrid',
] as const

const PUB_STATUS = [
  'published','published','published','published','published',
  'published','published','published','published','published',
  'published','published','published','published','published',
  'published','published','published','published','published',
  'published',
  'draft','draft','draft','draft',
] as const

// ── Domain definitions ───────────────────────────────────────────────────────

type DomainDef = {
  domain: string
  capabilities: readonly [string,string,string,string,string,string,string,string,string,string,string,string,string,string,string]
  apps: readonly { name: string; vendor: string }[]
}

const DOMAIN_DEFS: DomainDef[] = [
  {
    domain: 'Community Development',
    capabilities: [
      'Online Permitting',
      'Building Inspection Scheduling',
      'Business License Management',
      'Zoning & Land Use Management',
      'Code Enforcement Tracking',
      'Plan Review Management',
      'Certificate of Occupancy Issuance',
      'Subdivision & Platting',
      'Environmental Review Coordination',
      'Contractor License Verification',
      'Permit Fee Collection',
      'Permit Status Notifications',
      'Development Project Tracking',
      'Historic Preservation Review',
      'Variance & Appeal Processing',
    ],
    apps: [
      { name: 'Accela Civic Platform', vendor: 'Accela' },
      { name: 'Tyler EnerGov', vendor: 'Tyler Technologies' },
      { name: 'Cityworks Permits', vendor: 'Trimble' },
      { name: 'CivicPlus Permitting', vendor: 'CivicPlus' },
      { name: 'ViewPoint Cloud', vendor: 'ViewPoint' },
      { name: 'SmartGov Online', vendor: 'SmartGov' },
      { name: 'OpenGov Permitting', vendor: 'OpenGov' },
      { name: 'CSS ePlanning', vendor: 'CSS' },
      { name: 'POSSE Systems', vendor: 'Computronix' },
      { name: 'Citizenserve', vendor: 'Citizenserve' },
      { name: 'ProjectDox Plan Review', vendor: 'Avolve Software' },
      { name: 'E-PlanSoft Review', vendor: 'E-PlanSoft' },
      { name: 'Bluebeam Revu', vendor: 'Bluebeam' },
      { name: 'GovBiz Permits', vendor: 'GovBiz' },
      { name: 'OpenCounter Portal', vendor: 'OpenCounter' },
      { name: 'eCode360 Online', vendor: 'Municode' },
      { name: 'MyGov Permits', vendor: 'MyGov' },
      { name: 'Avolent ePermit', vendor: 'Avolent' },
      { name: 'DigitalBridge Permits', vendor: 'DigitalBridge' },
      { name: 'InspectTech Field', vendor: 'InspectTech' },
      { name: 'LicenseSifter Business Portal', vendor: 'LicenseSifter' },
      { name: 'Digi-Plan Reviewer', vendor: 'Digi-Plan' },
      { name: 'Streamline Permitting', vendor: 'Streamline' },
      { name: 'PlanHub Construction Portal', vendor: 'PlanHub' },
      { name: 'CivicHR Development Module', vendor: 'CivicHR' },
    ],
  },
  {
    domain: 'Public Safety',
    capabilities: [
      'Computer-Aided Dispatch',
      'Law Enforcement Records Management',
      'Body-Worn Camera Management',
      'Evidence Management',
      'Criminal Intelligence Analysis',
      'Field Incident Reporting',
      'Jail & Detention Management',
      'Animal Control Management',
      'Emergency Mass Notification',
      'Traffic Citation Processing',
      'Case Management (Investigations)',
      'Community Policing Outreach',
      'Tactical Resource Deployment',
      'Fire Incident Reporting',
      'Emergency Communications Logging',
    ],
    apps: [
      { name: 'Motorola PremierOne CAD', vendor: 'Motorola Solutions' },
      { name: 'Mark43 RMS', vendor: 'Mark43' },
      { name: 'Tyler New World CAD', vendor: 'Tyler Technologies' },
      { name: 'Axon Records', vendor: 'Axon' },
      { name: 'CentralSquare CAD', vendor: 'CentralSquare Technologies' },
      { name: 'Spillman Flex', vendor: 'Spillman Technologies' },
      { name: 'OSSI RMS', vendor: 'OSSI' },
      { name: 'Axon Evidence', vendor: 'Axon' },
      { name: 'VeriPic Evidence Management', vendor: 'VeriPic' },
      { name: 'TraCS Traffic Crash', vendor: 'Iowa DOT' },
      { name: 'ImageTrend Elite', vendor: 'ImageTrend' },
      { name: 'FireHouse Software', vendor: 'FireHouse Software' },
      { name: 'ESO Fire Incident', vendor: 'ESO' },
      { name: 'Tyler New World Jail', vendor: 'Tyler Technologies' },
      { name: 'Chameleon Animal Shelter', vendor: 'Chameleon' },
      { name: 'SilentPartner Animal Control', vendor: 'SilentPartner' },
      { name: 'TeleStaff Public Safety Scheduling', vendor: 'TeleStaff' },
      { name: 'Everbridge Emergency Notification', vendor: 'Everbridge' },
      { name: 'Rave Mobile Safety', vendor: 'Rave Mobile Safety' },
      { name: 'Tyler INCODE Court', vendor: 'Tyler Technologies' },
      { name: 'Motorola APX Mobile', vendor: 'Motorola Solutions' },
      { name: 'Vigilant License Plate Recognition', vendor: 'Motorola Solutions' },
      { name: 'ShotSpotter Gunshot Detection', vendor: 'ShotSpotter' },
      { name: 'Palantir Intelligence Analytics', vendor: 'Palantir' },
      { name: 'IAPro Internal Affairs', vendor: 'CI Technologies' },
    ],
  },
  {
    domain: 'Health & Human Services',
    capabilities: [
      'Benefits Eligibility Determination',
      'Social Services Case Management',
      'Child Welfare Management',
      'Foster Care & Adoption Tracking',
      'Adult Protective Services',
      'Behavioral Health Referral',
      'Public Health Disease Surveillance',
      'Immunization Registry Management',
      'Food Assistance Program Administration',
      'Homeless Services Coordination',
      'Veteran Services Coordination',
      'Disability Services Management',
      'WIC Program Administration',
      'Environmental Health Inspection',
      'Vital Records Management',
    ],
    apps: [
      { name: 'Netsmart myEvolv', vendor: 'Netsmart' },
      { name: 'Welligent Behavioral Health', vendor: 'Welligent' },
      { name: 'SAMS Social Assistance', vendor: 'SAMS' },
      { name: 'eCase Social Services', vendor: 'eCase' },
      { name: 'Northwoods Compass', vendor: 'Northwoods' },
      { name: 'MedCom Insight', vendor: 'MedCom' },
      { name: 'Maximus Case Management', vendor: 'Maximus' },
      { name: 'Tyler New World Benefits', vendor: 'Tyler Technologies' },
      { name: 'Apricot Social Solutions', vendor: 'Bonterra' },
      { name: 'Crossroads HMIS', vendor: 'Bitfocus' },
      { name: 'ServicePoint HMIS', vendor: 'Bitfocus' },
      { name: 'WIC Central', vendor: 'WIC Central' },
      { name: 'BenefitPoint Eligibility', vendor: 'BenefitPoint' },
      { name: 'Salesforce Health Cloud', vendor: 'Salesforce' },
      { name: 'Oracle HHS Cloud', vendor: 'Oracle' },
      { name: 'Cerner Behavioral Health', vendor: 'Oracle Cerner' },
      { name: 'HealthStream LMS', vendor: 'HealthStream' },
      { name: 'Rite-Solutions Case Management', vendor: 'Rite-Solutions' },
      { name: 'Verisk Health Analytics', vendor: 'Verisk' },
      { name: 'EvidenceNOW Practice Support', vendor: 'AHRQ' },
      { name: 'ImmTrac2 Immunization Registry', vendor: 'Texas DSHS' },
      { name: 'Vital Records Online', vendor: 'VitalChek' },
      { name: 'Accela Public Health', vendor: 'Accela' },
      { name: 'EHR (Community Health)', vendor: 'eClinicalWorks' },
      { name: 'CiviConnect Human Services Portal', vendor: 'CiviConnect' },
    ],
  },
  {
    domain: 'Finance & Procurement',
    capabilities: [
      'General Ledger Management',
      'Accounts Payable Processing',
      'Accounts Receivable Management',
      'Budget Planning & Forecasting',
      'Contract Management',
      'Vendor Management',
      'Purchasing & Requisition',
      'Capital Asset Management',
      'Grant Financial Management',
      'Payroll Processing',
      'Revenue Billing & Collection',
      'Financial Reporting',
      'Debt Management',
      'Purchasing Card Management',
      'Procurement Sourcing',
    ],
    apps: [
      { name: 'Tyler Munis ERP', vendor: 'Tyler Technologies' },
      { name: 'Oracle EBS Financials', vendor: 'Oracle' },
      { name: 'SAP Public Sector Finance', vendor: 'SAP' },
      { name: 'Workday Financial Management', vendor: 'Workday' },
      { name: 'OpenGov Financials', vendor: 'OpenGov' },
      { name: 'PeopleSoft Financials', vendor: 'Oracle' },
      { name: 'Questica Budget', vendor: 'Questica' },
      { name: 'Kaufman Hall Budget', vendor: 'Kaufman Hall' },
      { name: 'Periscope S2G Procurement', vendor: 'Periscope Holdings' },
      { name: 'DemandStar Procurement', vendor: 'DemandStar' },
      { name: 'Bonfire Procurement', vendor: 'Bonfire' },
      { name: 'SAP Ariba Procurement', vendor: 'SAP' },
      { name: 'Cobblestone Contract Management', vendor: 'CobbleStone Systems' },
      { name: 'AvidXchange AP Automation', vendor: 'AvidXchange' },
      { name: 'Bottomline Payment Hub', vendor: 'Bottomline Technologies' },
      { name: 'FIS Payment Solutions', vendor: 'FIS' },
      { name: 'Tyler Cashiering', vendor: 'Tyler Technologies' },
      { name: 'SunGard Public Sector Financials', vendor: 'Sungard AS' },
      { name: 'OpenGov Transparency Reporting', vendor: 'OpenGov' },
      { name: 'Tyler INCODE Finance', vendor: 'Tyler Technologies' },
      { name: 'Loomis Cash Management', vendor: 'Loomis' },
      { name: 'PayIt Government Payments', vendor: 'PayIt' },
      { name: 'Invoice Cloud Billing', vendor: 'Invoice Cloud' },
      { name: 'NIC ePayment', vendor: 'NIC' },
      { name: 'Tyler eGrants', vendor: 'Tyler Technologies' },
    ],
  },
  {
    domain: 'Legislative & Executive',
    capabilities: [
      'Agenda & Meeting Management',
      'Ordinance & Resolution Tracking',
      'Legislative Document Management',
      'Board & Commission Management',
      'Public Comment Management',
      'HR Self-Service',
      'Position Management & Workforce Planning',
      'Employee Performance Management',
      'Training & Certification Tracking',
      'Labor Relations Management',
      'Policy & Procedure Management',
      'Strategic Planning Support',
      'Executive Reporting & Dashboards',
      'Constituent Relationship Management',
      'Public Records Request Management',
    ],
    apps: [
      { name: 'Granicus govMeetings', vendor: 'Granicus' },
      { name: 'iCompass Agenda Management', vendor: 'iCompass' },
      { name: 'NovusAgenda', vendor: 'Novus' },
      { name: 'Legistar Legislative Management', vendor: 'Granicus' },
      { name: 'BoardEffect Governance', vendor: 'BoardEffect' },
      { name: 'NEOGOV Recruit', vendor: 'NEOGOV' },
      { name: 'NEOGOV Learn', vendor: 'NEOGOV' },
      { name: 'NEOGOV Onboard', vendor: 'NEOGOV' },
      { name: 'Oracle HCM Cloud', vendor: 'Oracle' },
      { name: 'Workday HCM', vendor: 'Workday' },
      { name: 'UKG Pro', vendor: 'UKG' },
      { name: 'ADP Workforce Now', vendor: 'ADP' },
      { name: 'Cornerstone Performance', vendor: 'Cornerstone OnDemand' },
      { name: 'PeopleAdmin Position Management', vendor: 'PeopleAdmin' },
      { name: 'ClearCompany Talent Management', vendor: 'ClearCompany' },
      { name: 'Tyler Munis HR', vendor: 'Tyler Technologies' },
      { name: 'CivicHR', vendor: 'CivicHR' },
      { name: 'BambooHR', vendor: 'BambooHR' },
      { name: 'GovQA Public Records', vendor: 'GovQA' },
      { name: 'NextRequest FOIA', vendor: 'NextRequest' },
      { name: 'Requestor Public Records', vendor: 'Requestor' },
      { name: 'Salesforce Constituent CRM', vendor: 'Salesforce' },
      { name: 'ClearPoint Strategy', vendor: 'ClearPoint' },
      { name: 'Infor Workforce Management', vendor: 'Infor' },
      { name: 'PolicyStat Policy Management', vendor: 'PolicyStat' },
    ],
  },
  {
    domain: 'Transportation & Infrastructure',
    capabilities: [
      'Road & Bridge Asset Management',
      'Infrastructure Work Order Management',
      'Fleet Management',
      'Traffic Signal Management',
      'Pavement Management',
      'Capital Project Management',
      'Right-of-Way Management',
      'Stormwater Management',
      'Transit Operations Management',
      'Parking Management',
      'Street Light Management',
      'Sign & Marking Inventory',
      'ADA Compliance Tracking',
      'Infrastructure Inspection',
      'Transportation Planning',
    ],
    apps: [
      { name: 'Cartegraph OMS', vendor: 'Cartegraph' },
      { name: 'Lucity Work Orders', vendor: 'Lucity' },
      { name: 'Trimble Cityworks', vendor: 'Trimble' },
      { name: 'Brightly Asset Essentials', vendor: 'Brightly' },
      { name: 'AssetWorks Fleet', vendor: 'AssetWorks' },
      { name: 'IBM Maximo', vendor: 'IBM' },
      { name: 'Hansen Infrastructure (IPS)', vendor: 'Hansen Technologies' },
      { name: 'InSync Traffic Control', vendor: 'InSync' },
      { name: 'Iteris Traffic Analytics', vendor: 'Iteris' },
      { name: 'Streetlight Data Analytics', vendor: 'Streetlight Data' },
      { name: 'Verizon Connect Fleet', vendor: 'Verizon Connect' },
      { name: 'Geotab Fleet Management', vendor: 'Geotab' },
      { name: 'Samsara Fleet Tracking', vendor: 'Samsara' },
      { name: 'Trapeze Transit Operations', vendor: 'Trapeze Group' },
      { name: 'Ecolane Transit Scheduling', vendor: 'Ecolane' },
      { name: 'Swiftly Transit Analytics', vendor: 'Swiftly' },
      { name: 'Masabi Fare Payments', vendor: 'Masabi' },
      { name: 'ParkMobile Parking', vendor: 'ParkMobile' },
      { name: 'GTechna Parking Enforcement', vendor: 'GTechna' },
      { name: 'Genetec AutoVu Parking', vendor: 'Genetec' },
      { name: 'OpenGov Capital Planning', vendor: 'OpenGov' },
      { name: 'e-Builder Capital Project Management', vendor: 'Trimble' },
      { name: 'Caltrans RMS (Roads)', vendor: 'Caltrans' },
      { name: 'VUEWorks Infrastructure', vendor: 'VUEWorks' },
      { name: 'Sidewalk Inspector Mobile', vendor: 'Sidewalk Inspector' },
    ],
  },
  {
    domain: 'Parks & Recreation',
    capabilities: [
      'Facility Reservation Management',
      'Program Registration & Enrollment',
      'Membership Management',
      'Park Asset Maintenance',
      'Athletic League Management',
      'Special Event Permitting',
      'Volunteer Management',
      'Rental & Concession Management',
      'Aquatics Program Management',
      'Senior Programs Coordination',
      'Trail & Open Space Management',
      'Equipment Inventory Management',
      'Youth Development Programs',
      'Outdoor Recreation Permitting',
      'Parks Grant & Donation Tracking',
    ],
    apps: [
      { name: 'ActiveNet Recreation', vendor: 'Active Network' },
      { name: 'Rec1 Recreation Management', vendor: 'Rec1' },
      { name: 'RecDesk', vendor: 'RecDesk' },
      { name: 'CivicRec', vendor: 'CivicPlus' },
      { name: 'PerfectMind Parks', vendor: 'PerfectMind' },
      { name: 'Vermont Systems RecTrac', vendor: 'Vermont Systems' },
      { name: 'Xplor Recreation', vendor: 'Xplor Technologies' },
      { name: 'Daxko Operations', vendor: 'Daxko' },
      { name: 'MyRec.com', vendor: 'MyRec' },
      { name: 'Sportsman Web Leagues', vendor: 'Sportsman Web' },
      { name: 'TeamSideline Leagues', vendor: 'TeamSideline' },
      { name: 'FMX Facility Management', vendor: 'FMX' },
      { name: 'EMS Software Events', vendor: 'EMS Software' },
      { name: 'Skedda Spaces', vendor: 'Skedda' },
      { name: 'WaiverSign Waivers', vendor: 'WaiverSign' },
      { name: 'GivePulse Volunteer Management', vendor: 'GivePulse' },
      { name: 'InitLive Event Volunteer', vendor: 'InitLive' },
      { name: 'Bloomerang Donations', vendor: 'Bloomerang' },
      { name: 'FrontStream Fundraising', vendor: 'FrontStream' },
      { name: 'Incode Parks & Rec', vendor: 'Tyler Technologies' },
      { name: 'Park Ranger Mobile Field', vendor: 'Park Ranger' },
      { name: 'Brightly Work Orders (Parks)', vendor: 'Brightly' },
      { name: 'iClass Pro Swim Academy', vendor: 'iClass Pro' },
      { name: 'ActiveCampaign Parks Comms', vendor: 'ActiveCampaign' },
      { name: 'Reserve America Camping', vendor: 'Reserve America' },
    ],
  },
  {
    domain: 'Economic Development',
    capabilities: [
      'Business Attraction & Retention',
      'Incentive Program Management',
      'Site Selection Support',
      'Small Business Assistance',
      'Workforce Development Coordination',
      'Tourism Program Management',
      'Economic Development Grant Administration',
      'Commercial Property Inventory',
      'Economic Intelligence & Analytics',
      'Innovation & Startup Ecosystem Support',
      'Foreign Direct Investment Tracking',
      'Opportunity Zone Management',
      'Brownfield Redevelopment Tracking',
      'Export Assistance Programs',
      'Regional Economic Planning',
    ],
    apps: [
      { name: 'GIS Planning SiteSeer', vendor: 'GIS Planning' },
      { name: 'Salesforce Nonprofit Success Pack', vendor: 'Salesforce' },
      { name: 'Esri Business Analyst Online', vendor: 'Esri' },
      { name: 'CoStar Group Analytics', vendor: 'CoStar' },
      { name: 'EMSI Labor Analytics', vendor: 'Lightcast' },
      { name: 'Stax Business Intelligence', vendor: 'Stax' },
      { name: 'SmartSimple Grants Management', vendor: 'SmartSimple' },
      { name: 'GrantStation Grants', vendor: 'GrantStation' },
      { name: 'Submittable Programs', vendor: 'Submittable' },
      { name: 'OpenGov CommunityConnect', vendor: 'OpenGov' },
      { name: 'IntelliChief Document Mgmt (ED)', vendor: 'IntelliChief' },
      { name: "Moody's Analytics CRE", vendor: "Moody's Analytics" },
      { name: 'Claritas Demographics', vendor: 'Claritas' },
      { name: 'Cvent Events Management', vendor: 'Cvent' },
      { name: 'Neighborly Community Development', vendor: 'Neighborly' },
      { name: 'Opportunity Zone Tracker', vendor: 'Custom Development' },
      { name: 'SizeUp Small Business', vendor: 'SizeUp' },
      { name: 'Liftoff Incentives Management', vendor: 'Liftoff' },
      { name: 'Vision Internet ED Portal', vendor: 'Vision Internet' },
      { name: 'Atlas Advertising ED', vendor: 'Atlas Advertising' },
      { name: 'Digital Air Strike Lead Capture', vendor: 'Digital Air Strike' },
      { name: 'LinkedIn Talent Insights', vendor: 'LinkedIn' },
      { name: 'BizTracker Business Registry', vendor: 'BizTracker' },
      { name: 'StartupGrid Ecosystem', vendor: 'StartupGrid' },
      { name: 'Burning Glass Labor Market', vendor: 'Burning Glass' },
    ],
  },
  {
    domain: 'Environmental Services',
    capabilities: [
      'Solid Waste & Recycling Management',
      'Hazardous Material Tracking',
      'Air Quality Monitoring',
      'Water Quality Monitoring',
      'Wastewater Treatment Management',
      'Stormwater Compliance Tracking',
      'Environmental Permit Management',
      'Green Building Program Administration',
      'Energy Management & Benchmarking',
      'Urban Forest Management',
      'Greenhouse Gas Inventory',
      'Environmental Education Programs',
      'Contaminated Site Remediation Tracking',
      'Vector Control Management',
      'Noise Complaint Management',
    ],
    apps: [
      { name: 'Accela Environmental Health', vendor: 'Accela' },
      { name: 'Tyler EnerGov Environmental', vendor: 'Tyler Technologies' },
      { name: 'OSIsoft PI System', vendor: 'OSIsoft' },
      { name: 'Intelex EHS Management', vendor: 'Intelex' },
      { name: 'Cority EHS', vendor: 'Cority' },
      { name: 'Enablon EHS Platform', vendor: 'Enablon' },
      { name: 'VelocityEHS', vendor: 'VelocityEHS' },
      { name: 'ProcessMAP EHS', vendor: 'ProcessMAP' },
      { name: 'Routemaster Route Optimization', vendor: 'Routemaster' },
      { name: 'Rubicon Smart Waste', vendor: 'Rubicon' },
      { name: 'Republic Services Digital', vendor: 'Republic Services' },
      { name: 'Cascades Waste Analytics', vendor: 'Cascades' },
      { name: 'BeWhere Asset Tracking', vendor: 'BeWhere' },
      { name: 'EPA eManifest Integration', vendor: 'US EPA' },
      { name: 'Veolia Digital SCADA', vendor: 'Veolia' },
      { name: 'RCRA Info Integration', vendor: 'US EPA' },
      { name: 'InControl SCADA', vendor: 'InControl' },
      { name: 'Cityworks Environmental WO', vendor: 'Trimble' },
      { name: 'Portfolio Manager (Energy Star)', vendor: 'US EPA' },
      { name: 'Lucid Energy Management', vendor: 'Lucid' },
      { name: 'OpenEnvironment Hazmat', vendor: 'OpenEnvironment' },
      { name: 'ArborPro Tree Inventory', vendor: 'ArborPro' },
      { name: 'i-Tree Urban Forest', vendor: 'i-Tree' },
      { name: 'GHG Protocol Calculator', vendor: 'Custom Development' },
      { name: 'Vector Solutions EHS Training', vendor: 'Vector Solutions' },
    ],
  },
  {
    domain: 'Administration & Operations',
    capabilities: [
      'Document Management',
      'Records Retention & Disposition',
      'Mail & Communications Management',
      'Printing & Publishing Services',
      'Facility Management',
      'Space Planning & Allocation',
      'Inventory & Supply Management',
      'Telecommunications Management',
      'Visitor & Access Management',
      'Risk Management & Insurance',
      'Emergency Management Planning',
      'Business Continuity Management',
      'Internal Audit Management',
      'Compliance & Ethics Reporting',
      'Fleet Scheduling & Dispatch',
    ],
    apps: [
      { name: 'Laserfiche ECM', vendor: 'Laserfiche' },
      { name: 'Hyland OnBase', vendor: 'Hyland' },
      { name: 'DocuWare', vendor: 'DocuWare' },
      { name: 'OpenText Content Suite', vendor: 'OpenText' },
      { name: 'Microsoft SharePoint', vendor: 'Microsoft' },
      { name: 'M-Files Document Management', vendor: 'M-Files' },
      { name: 'Box Government', vendor: 'Box' },
      { name: 'Iron Mountain Digital', vendor: 'Iron Mountain' },
      { name: 'Nuxeo Content Platform', vendor: 'Nuxeo' },
      { name: 'Tyler Munis Inventory', vendor: 'Tyler Technologies' },
      { name: 'EZOfficeInventory', vendor: 'EZOfficeInventory' },
      { name: 'Limble CMMS', vendor: 'Limble' },
      { name: 'eMaint CMMS', vendor: 'Fluke Reliability' },
      { name: 'Gatekeeper Contract Lifecycle', vendor: 'Gatekeeper' },
      { name: 'Ironclad Contracts', vendor: 'Ironclad' },
      { name: 'TRIRIGA Facilities (IBM)', vendor: 'IBM' },
      { name: 'FM:Systems Facility Management', vendor: 'FM:Systems' },
      { name: 'Planon Workplace Management', vendor: 'Planon' },
      { name: 'Visitor Management System (Envoy)', vendor: 'Envoy' },
      { name: 'Genfare Fare & Access', vendor: 'Genfare' },
      { name: 'Riskonnect Risk Management', vendor: 'Riskonnect' },
      { name: 'Tyler Risk Manager', vendor: 'Tyler Technologies' },
      { name: 'Resolver Audit Management', vendor: 'Resolver' },
      { name: 'NAVEX EthicsPoint', vendor: 'NAVEX Global' },
      { name: 'Rave Emergency Management', vendor: 'Rave Mobile Safety' },
    ],
  },
  {
    domain: 'Housing & Community Services',
    capabilities: [
      'Affordable Housing Registry',
      'Housing Assistance Program Administration',
      'Tenant & Landlord Mediation',
      'Housing Choice Voucher Management',
      'CDBG Grant Management',
      'Neighborhood Revitalization Planning',
      'Homeless Housing Placement',
      'Fair Housing Complaint Tracking',
      'Rental Inspection Program',
      'Down Payment Assistance Program',
      'Housing Rehabilitation Program',
      'Senior Housing Services',
      'Community Land Trust Management',
      'Housing Market Analysis',
      'Supportive Services Coordination',
    ],
    apps: [
      { name: 'Yardi Affordable Housing', vendor: 'Yardi Systems' },
      { name: 'MRI Residential', vendor: 'MRI Software' },
      { name: 'RealPage Affordable Housing', vendor: 'RealPage' },
      { name: 'Emphasys Elite Housing Authority', vendor: 'Emphasys' },
      { name: 'Lindsey Software Affordable', vendor: 'Lindsey Software' },
      { name: 'Tenmast WinTen2+', vendor: 'Tenmast Software' },
      { name: 'Bitfocus Clarity HMIS', vendor: 'Bitfocus' },
      { name: 'WellSky Housing Support', vendor: 'WellSky' },
      { name: 'Eccovia ClientTrack', vendor: 'Eccovia' },
      { name: 'CaseWorthy Housing', vendor: 'CaseWorthy' },
      { name: 'Neighborly Grants', vendor: 'Neighborly' },
      { name: 'GrantSolutions Housing', vendor: 'GrantSolutions' },
      { name: 'ShelterManager Shelter', vendor: 'ShelterManager' },
      { name: 'Yardi Voyager Affordable', vendor: 'Yardi Systems' },
      { name: 'WayPoint Housing Services', vendor: 'WayPoint' },
      { name: 'Public Housing Tracking (Custom)', vendor: 'Custom Development' },
      { name: 'Accela Rental Inspections', vendor: 'Accela' },
      { name: 'NeighborWorks Network Portal', vendor: 'NeighborWorks' },
      { name: 'SUMS State Housing System', vendor: 'State Housing' },
      { name: 'OpenGov Housing Portal', vendor: 'OpenGov' },
      { name: 'Salesforce Housing CRM', vendor: 'Salesforce' },
      { name: 'CoStar Housing Analytics', vendor: 'CoStar' },
      { name: 'HUD IDIS Integration', vendor: 'US HUD' },
      { name: 'HUD PIC Integration', vendor: 'US HUD' },
      { name: 'Spectrum Affordable Housing', vendor: 'Spectrum' },
    ],
  },
  {
    domain: 'Education & Libraries',
    capabilities: [
      'Library Catalog & Discovery',
      'Digital Resource Access Management',
      'Patron Account Management',
      'Interlibrary Loan Management',
      'Community Learning Program Scheduling',
      'Digital Literacy Training Programs',
      'Early Literacy Program Management',
      'Youth Services Coordination',
      'Community Partnership Management',
      'Library Asset Inventory',
      'E-Government Services Access',
      'Digital Equity Program Management',
      'Maker Space Scheduling',
      'Outreach & Mobile Services Tracking',
      'Collection Development Management',
    ],
    apps: [
      { name: 'Polaris ILS', vendor: 'Innovative Interfaces' },
      { name: 'Koha Open Source ILS', vendor: 'ByWater Solutions' },
      { name: 'Evergreen ILS', vendor: 'Equinox Open Library Initiative' },
      { name: 'Sierra Library Services', vendor: 'Innovative Interfaces' },
      { name: 'Alma Library Services', vendor: 'Ex Libris' },
      { name: 'FOLIO Library Services', vendor: 'FOLIO' },
      { name: 'OverDrive Libby', vendor: 'OverDrive' },
      { name: 'hoopla Digital', vendor: 'Midwest Tape' },
      { name: 'Kanopy Streaming', vendor: 'Kanopy' },
      { name: 'RBdigital', vendor: 'RBdigital' },
      { name: 'EnvisionWare Public Access', vendor: 'EnvisionWare' },
      { name: 'Comprise Technologies', vendor: 'Comprise Technologies' },
      { name: 'Springshare LibGuides', vendor: 'Springshare' },
      { name: 'LibAnswers Reference', vendor: 'Springshare' },
      { name: 'LibCal Scheduling', vendor: 'Springshare' },
      { name: 'SirsiDynix Workflows', vendor: 'SirsiDynix' },
      { name: 'TLC Library Solution', vendor: 'The Library Corporation' },
      { name: 'PC Reservation (Library)', vendor: 'PC Reservation' },
      { name: 'Freading eBooks', vendor: 'OverDrive' },
      { name: 'Spectrum RFID Library', vendor: 'Spectrum' },
      { name: 'Communico Library Apps', vendor: 'Communico' },
      { name: 'BiblioCommons Discovery', vendor: 'BiblioCommons' },
      { name: 'Innovative Decisions Inc. Analytics', vendor: 'IDI' },
      { name: 'Learning Express Library', vendor: 'Learning Express' },
      { name: 'ProQuest Databases', vendor: 'ProQuest' },
    ],
  },
  {
    domain: 'Information Technology',
    capabilities: [
      'Service Desk & IT Support',
      'IT Asset Management',
      'IT Change Management',
      'Configuration Management (CMDB)',
      'IT Project Portfolio Management',
      'Software License Management',
      'Network Management & Monitoring',
      'Server & Infrastructure Management',
      'Backup & Recovery Management',
      'IT Procurement Management',
      'GIS Services & Mapping',
      'Print Services Management',
      'Video Conferencing & Collaboration',
      'IT Training & Documentation',
      'Technology Standards Management',
    ],
    apps: [
      { name: 'ServiceNow ITSM', vendor: 'ServiceNow' },
      { name: 'Jira Service Management', vendor: 'Atlassian' },
      { name: 'Freshservice ITSM', vendor: 'Freshworks' },
      { name: 'SolarWinds Service Desk', vendor: 'SolarWinds' },
      { name: 'ManageEngine ServiceDesk Plus', vendor: 'ManageEngine' },
      { name: 'Zendesk Support', vendor: 'Zendesk' },
      { name: 'SolarWinds Network Monitoring', vendor: 'SolarWinds' },
      { name: 'PRTG Network Monitor', vendor: 'Paessler' },
      { name: 'Nagios XI', vendor: 'Nagios' },
      { name: 'SolarWinds Server & App Monitor', vendor: 'SolarWinds' },
      { name: 'SolarWinds Patch Manager', vendor: 'SolarWinds' },
      { name: 'ManageEngine Patch Manager Plus', vendor: 'ManageEngine' },
      { name: 'BigFix Endpoint Management', vendor: 'HCL Technologies' },
      { name: 'Ivanti Patch Management', vendor: 'Ivanti' },
      { name: 'Esri ArcGIS Enterprise', vendor: 'Esri' },
      { name: 'Esri ArcGIS Pro', vendor: 'Esri' },
      { name: 'GovQA FOIA (IT)', vendor: 'GovQA' },
      { name: 'ManageEngine IT Analytics', vendor: 'ManageEngine' },
      { name: 'Cisco WebEx', vendor: 'Cisco' },
      { name: 'Microsoft Teams', vendor: 'Microsoft' },
      { name: 'Zoom Government', vendor: 'Zoom' },
      { name: 'GIS Cloud Portal', vendor: 'GIS Cloud' },
      { name: 'Flexera SLM', vendor: 'Flexera' },
      { name: 'Snow Software License Manager', vendor: 'Snow Software' },
      { name: 'Snipe-IT Asset Manager', vendor: 'Snipe-IT' },
    ],
  },
  {
    domain: 'Platform & Infrastructure',
    capabilities: [
      'Cloud Infrastructure Management',
      'Container Orchestration',
      'Database Administration',
      'Storage Management',
      'Network Security Operations',
      'Load Balancing & Traffic Management',
      'Disaster Recovery Operations',
      'Patch & Update Management',
      'Virtualization Management',
      'API Gateway Management',
      'Middleware & Integration Platform',
      'Monitoring & Observability',
      'Log Management & Analytics',
      'Infrastructure as Code Management',
      'Capacity Planning & Optimization',
    ],
    apps: [
      { name: 'VMware vSphere', vendor: 'VMware' },
      { name: 'VMware NSX', vendor: 'VMware' },
      { name: 'Nutanix AHV', vendor: 'Nutanix' },
      { name: 'Citrix Virtual Apps', vendor: 'Citrix' },
      { name: 'Microsoft Hyper-V', vendor: 'Microsoft' },
      { name: 'AWS GovCloud', vendor: 'Amazon Web Services' },
      { name: 'Microsoft Azure Government', vendor: 'Microsoft' },
      { name: 'Google Cloud Public Sector', vendor: 'Google' },
      { name: 'F5 BIG-IP Load Balancer', vendor: 'F5 Networks' },
      { name: 'Cisco APIC', vendor: 'Cisco' },
      { name: 'Palo Alto Panorama', vendor: 'Palo Alto Networks' },
      { name: 'Fortinet FortiManager', vendor: 'Fortinet' },
      { name: 'Zabbix Monitoring', vendor: 'Zabbix' },
      { name: 'Datadog Infrastructure', vendor: 'Datadog' },
      { name: 'Splunk Enterprise', vendor: 'Splunk' },
      { name: 'Dynatrace APM', vendor: 'Dynatrace' },
      { name: 'AppDynamics', vendor: 'Cisco' },
      { name: 'Veritas NetBackup', vendor: 'Veritas' },
      { name: 'Veeam Backup & Replication', vendor: 'Veeam' },
      { name: 'CommVault Backup', vendor: 'CommVault' },
      { name: 'Cohesity DataProtect', vendor: 'Cohesity' },
      { name: 'Pure Storage FlashArray', vendor: 'Pure Storage' },
      { name: 'NetApp ONTAP', vendor: 'NetApp' },
      { name: 'Dell EMC PowerProtect', vendor: 'Dell Technologies' },
      { name: 'Red Hat OpenShift', vendor: 'Red Hat' },
    ],
  },
  {
    domain: 'Data & Integration',
    capabilities: [
      'Master Data Management',
      'Data Warehouse Management',
      'ETL & Data Pipeline Management',
      'Business Intelligence & Analytics',
      'Data Governance & Stewardship',
      'Open Data Portal Management',
      'Real-Time Data Streaming',
      'Data Quality Management',
      'Metadata Management',
      'Data Catalog Management',
      'API Management & Documentation',
      'System Integration (EAI/ESB)',
      'Data Privacy & Consent Management',
      'Reporting & Dashboard Distribution',
      'Geospatial Data Management',
    ],
    apps: [
      { name: 'Informatica PowerCenter', vendor: 'Informatica' },
      { name: 'Talend Data Integration', vendor: 'Talend' },
      { name: 'IBM DataStage', vendor: 'IBM' },
      { name: 'MuleSoft Anypoint Platform', vendor: 'MuleSoft' },
      { name: 'Dell Boomi Integration', vendor: 'Dell Boomi' },
      { name: 'Azure Data Factory', vendor: 'Microsoft' },
      { name: 'AWS Glue ETL', vendor: 'Amazon Web Services' },
      { name: 'Snowflake Data Warehouse', vendor: 'Snowflake' },
      { name: 'Azure Synapse Analytics', vendor: 'Microsoft' },
      { name: 'AWS Redshift', vendor: 'Amazon Web Services' },
      { name: 'IBM Db2 Warehouse', vendor: 'IBM' },
      { name: 'Tableau Server', vendor: 'Salesforce' },
      { name: 'Power BI Premium', vendor: 'Microsoft' },
      { name: 'Qlik Sense Enterprise', vendor: 'Qlik' },
      { name: 'MicroStrategy Government', vendor: 'MicroStrategy' },
      { name: 'SAP BusinessObjects', vendor: 'SAP' },
      { name: 'SAS Viya Analytics', vendor: 'SAS' },
      { name: 'Socrata Open Data', vendor: 'Tyler Technologies' },
      { name: 'CKAN Open Data Portal', vendor: 'CKAN' },
      { name: 'Esri ArcGIS Hub', vendor: 'Esri' },
      { name: 'Collibra Data Governance', vendor: 'Collibra' },
      { name: 'Informatica Axon Data Governance', vendor: 'Informatica' },
      { name: 'Alation Data Catalog', vendor: 'Alation' },
      { name: 'Atlan Data Catalog', vendor: 'Atlan' },
      { name: 'Apache Kafka Streaming', vendor: 'Apache Foundation' },
    ],
  },
  {
    domain: 'Cybersecurity',
    capabilities: [
      'Security Information & Event Management',
      'Endpoint Detection & Response',
      'Vulnerability Management',
      'Identity Threat Detection',
      'Security Awareness Training',
      'Incident Response Management',
      'Security Policy Management',
      'Third-Party Risk Management',
      'Data Loss Prevention',
      'Network Access Control',
      'SOC Operations Management',
      'Threat Intelligence Management',
      'Compliance & Audit Support (Security)',
      'Zero Trust Architecture Management',
      'Penetration Testing Management',
    ],
    apps: [
      { name: 'CrowdStrike Falcon', vendor: 'CrowdStrike' },
      { name: 'SentinelOne Singularity', vendor: 'SentinelOne' },
      { name: 'Microsoft Defender for Endpoint', vendor: 'Microsoft' },
      { name: 'Carbon Black Enterprise', vendor: 'VMware' },
      { name: 'Palo Alto Cortex XDR', vendor: 'Palo Alto Networks' },
      { name: 'Splunk SIEM', vendor: 'Splunk' },
      { name: 'IBM QRadar', vendor: 'IBM' },
      { name: 'LogRhythm SIEM', vendor: 'LogRhythm' },
      { name: 'Sumo Logic Cloud SIEM', vendor: 'Sumo Logic' },
      { name: 'Microsoft Sentinel', vendor: 'Microsoft' },
      { name: 'Tenable.io Vulnerability Management', vendor: 'Tenable' },
      { name: 'Qualys VMDR', vendor: 'Qualys' },
      { name: 'Rapid7 InsightVM', vendor: 'Rapid7' },
      { name: 'Tripwire Enterprise', vendor: 'Fortra' },
      { name: 'Forcepoint DLP', vendor: 'Forcepoint' },
      { name: 'Symantec DLP', vendor: 'Broadcom' },
      { name: 'Digital Guardian DLP', vendor: 'Fortra' },
      { name: 'Proofpoint Email Security', vendor: 'Proofpoint' },
      { name: 'Mimecast Email Security', vendor: 'Mimecast' },
      { name: 'Cisco Umbrella', vendor: 'Cisco' },
      { name: 'Zscaler Internet Access', vendor: 'Zscaler' },
      { name: 'KnowBe4 Security Awareness', vendor: 'KnowBe4' },
      { name: 'Proofpoint Security Awareness', vendor: 'Proofpoint' },
      { name: 'ServiceNow SecOps', vendor: 'ServiceNow' },
      { name: 'Archer GRC Platform', vendor: 'RSA' },
    ],
  },
  {
    domain: 'Digital Services',
    capabilities: [
      'Citizen-Facing Web Portal Management',
      'Mobile Application Delivery',
      'Digital Forms Management',
      'Online Payment Processing',
      'Chatbot & Virtual Assistant',
      'Digital Accessibility Compliance',
      'Website Content Management',
      'Push Notification Management',
      'Digital Identity Verification',
      'eSignature Services',
      'Digital Record Delivery',
      'User Experience Research & Testing',
      'Digital Inclusion Programs',
      'Multi-Channel Service Delivery',
      'Digital Analytics & Performance Monitoring',
    ],
    apps: [
      { name: 'Granicus govAccess Web CMS', vendor: 'Granicus' },
      { name: 'CivicPlus CMS', vendor: 'CivicPlus' },
      { name: 'Sitecore Experience Platform', vendor: 'Sitecore' },
      { name: 'Adobe Experience Manager', vendor: 'Adobe' },
      { name: 'Drupal Government Edition', vendor: 'Acquia' },
      { name: 'Salesforce Experience Cloud', vendor: 'Salesforce' },
      { name: 'Microsoft Power Pages', vendor: 'Microsoft' },
      { name: 'Granicus GovDelivery', vendor: 'Granicus' },
      { name: 'Twilio SMS Communications', vendor: 'Twilio' },
      { name: 'Qualtrics XM Government', vendor: 'Qualtrics' },
      { name: 'SurveyMonkey Enterprise', vendor: 'SurveyMonkey' },
      { name: 'FormAssembly Forms', vendor: 'FormAssembly' },
      { name: 'Formstack Forms', vendor: 'Formstack' },
      { name: 'DocuSign eSignature', vendor: 'DocuSign' },
      { name: 'Adobe Sign', vendor: 'Adobe' },
      { name: 'HelloSign', vendor: 'Dropbox' },
      { name: 'NICE CXone Contact Center', vendor: 'NICE' },
      { name: 'Genesys Cloud CX', vendor: 'Genesys' },
      { name: 'Zendesk Government CX', vendor: 'Zendesk' },
      { name: 'Google Analytics 4 (Gov)', vendor: 'Google' },
      { name: 'Adobe Analytics Government', vendor: 'Adobe' },
      { name: 'Siteimprove Digital Quality', vendor: 'Siteimprove' },
      { name: 'Userway Accessibility Widget', vendor: 'Userway' },
      { name: 'PayIt Digital Government', vendor: 'PayIt' },
      { name: 'NIC Digital Services', vendor: 'NIC' },
    ],
  },
  {
    domain: 'Enterprise Architecture',
    capabilities: [
      'Application Portfolio Management',
      'Capability Map Management',
      'Architecture Decision Management',
      'Architecture Principles Management',
      'Technology Roadmap Management',
      'Business Process Modelling',
      'Architecture Review Board Operations',
      'Enterprise Data Model Management',
      'Integration Architecture Management',
      'Reference Architecture Management',
      'Architecture Governance & Compliance',
      'Vendor & Technology Assessment',
      'Architecture Debt Tracking',
      'Solution Design Review',
      'Digital Strategy Planning',
    ],
    apps: [
      { name: 'Ardoq Enterprise Architecture', vendor: 'Ardoq' },
      { name: 'LeanIX EAM', vendor: 'LeanIX' },
      { name: 'BiZZdesign Enterprise Studio', vendor: 'BiZZdesign' },
      { name: 'MEGA HOPEX', vendor: 'MEGA International' },
      { name: 'Alfabet Software AG', vendor: 'Software AG' },
      { name: 'Sparx Enterprise Architect', vendor: 'Sparx Systems' },
      { name: 'Orbus iServer', vendor: 'Orbus Software' },
      { name: 'Planview Enterprise One', vendor: 'Planview' },
      { name: 'ServiceNow EA Management', vendor: 'ServiceNow' },
      { name: 'ADOIT Enterprise Architecture', vendor: 'BOC Group' },
      { name: 'Avolution ABACUS', vendor: 'Avolution' },
      { name: 'Erwin Data Modeler', vendor: 'Quest' },
      { name: 'iGrafx Process360', vendor: 'iGrafx' },
      { name: 'Signavio Process Manager', vendor: 'SAP' },
      { name: 'Celonis Process Mining', vendor: 'Celonis' },
      { name: 'ARIS by Software AG', vendor: 'Software AG' },
      { name: 'Camunda Workflow Engine', vendor: 'Camunda' },
      { name: 'Pega Platform', vendor: 'Pegasystems' },
      { name: 'Appian Business Process', vendor: 'Appian' },
      { name: 'MooD Business Analysis', vendor: 'MooD International' },
      { name: 'ValueBlue BlueDolphin', vendor: 'ValueBlue' },
      { name: 'Essential Architecture Manager', vendor: 'Essential Project' },
      { name: 'Capsifi Jalapeno', vendor: 'Capsifi' },
      { name: 'Bizzdesign Horizzon', vendor: 'BiZZdesign' },
      { name: 'Planview EA', vendor: 'Planview' },
    ],
  },
  {
    domain: 'Identity & Access Management',
    capabilities: [
      'Single Sign-On Management',
      'Multi-Factor Authentication Management',
      'Directory Services Management',
      'Privileged Access Management',
      'Role-Based Access Control Management',
      'Identity Lifecycle Management',
      'Guest & Federated Identity Management',
      'Credential Management',
      'Access Certification & Review',
      'Identity Governance Management',
      'Password Policy Enforcement',
      'Service Account Management',
      'Certificate & PKI Management',
      'Identity Analytics & Risk Scoring',
      'Resident Identity Verification',
    ],
    apps: [
      { name: 'Microsoft Active Directory', vendor: 'Microsoft' },
      { name: 'Microsoft Entra ID', vendor: 'Microsoft' },
      { name: 'Okta Workforce Identity', vendor: 'Okta' },
      { name: 'Ping Identity PingFederate', vendor: 'Ping Identity' },
      { name: 'SailPoint IdentityNow', vendor: 'SailPoint' },
      { name: 'One Identity Manager', vendor: 'One Identity' },
      { name: 'Saviynt Identity Governance', vendor: 'Saviynt' },
      { name: 'CyberArk PAM', vendor: 'CyberArk' },
      { name: 'BeyondTrust Privileged Access', vendor: 'BeyondTrust' },
      { name: 'Delinea Secret Server', vendor: 'Delinea' },
      { name: 'ForgeRock Identity Platform', vendor: 'ForgeRock' },
      { name: 'IBM Security Verify', vendor: 'IBM' },
      { name: 'RSA SecurID', vendor: 'RSA Security' },
      { name: 'Duo Security MFA', vendor: 'Cisco' },
      { name: 'Yubico YubiKey Management', vendor: 'Yubico' },
      { name: 'HID Global IAM', vendor: 'HID Global' },
      { name: 'Entrust Identity Enterprise', vendor: 'Entrust' },
      { name: 'Radiant Logic RadiantOne', vendor: 'Radiant Logic' },
      { name: 'Omada Identity Suite', vendor: 'Omada' },
      { name: 'EmpowerID', vendor: 'EmpowerID' },
      { name: 'Fischer Identity', vendor: 'Fischer International' },
      { name: 'SecureAuth IdP', vendor: 'SecureAuth' },
      { name: 'Avatier Identity Anywhere', vendor: 'Avatier' },
      { name: 'ManageEngine ADManager Plus', vendor: 'ManageEngine' },
      { name: 'Thycotic Secret Server', vendor: 'Delinea' },
    ],
  },
  {
    domain: 'Cloud & DevOps',
    capabilities: [
      'CI/CD Pipeline Management',
      'Source Code Repository Management',
      'Automated Testing Management',
      'Release & Deployment Management',
      'Environment Provisioning',
      'Cloud Cost Management',
      'Infrastructure Automation',
      'DevSecOps Integration',
      'Artifact Repository Management',
      'Feature Flag Management',
      'Application Performance Monitoring',
      'Cloud Migration Management',
      'Site Reliability Engineering',
      'Configuration & Secret Management',
      'Developer Portal & Documentation',
    ],
    apps: [
      { name: 'GitHub Enterprise', vendor: 'GitHub' },
      { name: 'GitLab Self-Managed', vendor: 'GitLab' },
      { name: 'Azure DevOps', vendor: 'Microsoft' },
      { name: 'Bitbucket Server', vendor: 'Atlassian' },
      { name: 'Jenkins CI/CD', vendor: 'Jenkins' },
      { name: 'CircleCI', vendor: 'CircleCI' },
      { name: 'TeamCity', vendor: 'JetBrains' },
      { name: 'HashiCorp Terraform', vendor: 'HashiCorp' },
      { name: 'Ansible Automation Platform', vendor: 'Red Hat' },
      { name: 'Puppet Enterprise', vendor: 'Puppet' },
      { name: 'Chef Automate', vendor: 'Progress' },
      { name: 'JFrog Artifactory', vendor: 'JFrog' },
      { name: 'Nexus Repository Manager', vendor: 'Sonatype' },
      { name: 'SonarQube Code Quality', vendor: 'SonarSource' },
      { name: 'Checkmarx SAST', vendor: 'Checkmarx' },
      { name: 'Veracode Security Testing', vendor: 'Veracode' },
      { name: 'Jira Software (Dev)', vendor: 'Atlassian' },
      { name: 'Confluence (Dev Docs)', vendor: 'Atlassian' },
      { name: 'PagerDuty Incident Management', vendor: 'PagerDuty' },
      { name: 'LaunchDarkly Feature Flags', vendor: 'LaunchDarkly' },
      { name: 'HashiCorp Vault', vendor: 'HashiCorp' },
      { name: 'Backstage Developer Portal', vendor: 'Spotify' },
      { name: 'OpsLevel Service Catalog', vendor: 'OpsLevel' },
      { name: 'Kubecost Cloud Cost', vendor: 'Kubecost' },
      { name: 'Apigee API Management', vendor: 'Google' },
    ],
  },
]

// ── Exported fixtures ────────────────────────────────────────────────────────

export type ScaleCapability = {
  name: string
  description: string
  domain: string
  status: 'draft' | 'published' | 'archived'
  visibility: 'org'
  personas: string[]
}

export type ScaleApplication = {
  name: string
  description: string
  vendor: string
  hostingModel: 'saas' | 'on-prem' | 'hybrid'
  lifecycleStatus: 'active' | 'planned' | 'sunset' | 'decommissioned'
  status: 'draft' | 'published' | 'archived'
  capabilities: string[]
}

export const SCALE_CAPABILITIES: ScaleCapability[] = DOMAIN_DEFS.flatMap(({ domain, capabilities }) =>
  capabilities.map(name => ({
    name,
    description: `${name} supporting ${domain} services.`,
    domain,
    status: 'published',
    visibility: 'org',
    personas: [],
  }))
)

export const SCALE_APPLICATIONS: ScaleApplication[] = DOMAIN_DEFS.flatMap(({ capabilities, apps }) =>
  apps.map(({ name, vendor }, i) => {
    // Distribute capability links: apps 0–8 → 1 cap, 9–17 → 2 caps, 18–24 → 3 caps
    const numCaps = i < 9 ? 1 : i < 18 ? 2 : 3
    const capLinks = Array.from({ length: numCaps }, (_, k) =>
      capabilities[(i + k * 5) % capabilities.length]
    )
    return {
      name,
      description: `${name} — enterprise platform for ${capabilities[i % capabilities.length]} and related services.`,
      vendor,
      hostingModel: HOSTING[i],
      lifecycleStatus: LIFECYCLE[i],
      status: PUB_STATUS[i],
      capabilities: capLinks,
    }
  })
)
